services:
  - type: web
    name: carryspanner-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: APPWRITE_ENDPOINT
        value: https://fra.cloud.appwrite.io/v1
      - key: APPWRITE_PROJECT_ID
        sync: false
      - key: APPWRITE_API_KEY
        sync: false
      - key: APPWRITE_DB_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: APP_NAME
        value: CarrySpanner API
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        sync: false
      - key: HUBTEL_CLIENT_ID
        sync: false
      - key: HUBTEL_CLIENT_SECRET
        sync: false
      - key: HUBTEL_SENDER_ID
        value: CarrySpanner
